#!/bin/bash

dbus-send --session \
--dest=org.freedesktop.DBus \
--type=method_call \
--print-reply \
/org/freedesktop/DBus \
org.freedesktop.DBus.ListNames | sed -ne '/MediaPlayer/{s/string//;s/^\s*//g;p}' | xargs | sed 's/\s/,/g'
