#!/bin/bash

dbus-send \
--print-reply \
--dest=$1 \
/org/mpris/MediaPlayer2 \
org.freedesktop.DBus.Properties.Get \
string:'org.mpris.MediaPlayer2.Player' \
string:'Metadata' | sed -ne '/title/{n;s/string //;s/variant//;s/"//g;s/^\s*//g;p}'